//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_SkiLift.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiftUsageHistory
    {
        public int ID { get; set; }
        public int TicketID { get; set; }
        public int SkiLiftID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual SkiLift Lift { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
