//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_SkiLift.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTariff
    {
        public int ID { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public double PointPrice { get; set; }
        public double HourPrice { get; set; }
    }
}
