//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_SkiLift.Models
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Ticket
    {
        public int ID { get; set; }
        public bool IsValid { get; set; }
        public System.DateTime DateAdded { get; set; }
        public double PriceSold { get; set; }
    }
}
